style = "full"             # auto, full, compact the style of the UI
inline_height = 0          # number of lines to use in inline mode
invert = false             # true/false whether to invert the UI
enter_accept = true        # true/false whether pressing enter auto runs the selected command
keymap_mode = "vim-insert" # vim-insert/vim-normal
